on:
  push:
    branches:
      - main
    paths:
      - 'Add-AzFirewallRule/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Untrusted
          Install-Module Az.Accounts, Az.Synapse, Az.Sql -Force
      - name: Publish to PSGallery
        uses: pcgeek86/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.PSGALLERY_APIKEY }}
          
